services:
  # MySQL (User Service DB)
  db_userservice:
    image: mysql:latest
    container_name: word_wise
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=word_wise
    ports:
      - "3307:3306"
    volumes:
      - word_wise_data:/var/lib/mysql
    networks:
      - word_wise
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Kafka
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - word_wise
    volumes:
      - kafka_data:/bitnami/kafka

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - word_wise
    volumes:
      - kafka_ui_data:/etc/kafkaui

  # Redis
  redis:
    image: redis:7
    container_name: wordwise-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data

volumes:
  word_wise_data:   # MySQL data
  kafka_data:       # Kafka data
  kafka_ui_data:    # Kafka UI config
  redis-data:

networks:
  word_wise:
    driver: bridge
