services:
  db_userservice:
    image: mysql:latest
    container_name: word_wise
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: word_wise
      # Tắt SSL mặc định để client không bị lỗi
      MYSQL_SSL_CA: ""
      MYSQL_SSL_CERT: ""
      MYSQL_SSL_KEY: ""
    ports:
      - "3307:3306"   # host:container
    volumes:
      - wordwise_data:/var/lib/mysql   # named volume, tránh lỗi permission
    networks:
      - word_wise
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  word_wise:
    driver: bridge

volumes:
  wordwise_data:   # Docker tự quản lý, nằm trên Linux filesystem
