spring.application.name=core-word-wise
spring.datasource.url=jdbc:mysql://word-wise-mysql-word-wise.j.aivencloud.com:15903/word_wise?autoReconnect=true&useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_I7K1IxM116Pm-8274Dh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=EMUBJ4aXQgDYJy78h7oSLyKBckTUVsks6dPYDiTMVg6
jwt.expiration=86400000
jwt.extension.expiration=31536000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=milkstoremanagement@gmail.com
spring.mail.password=wzve laqb gfoo jjwp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

springdoc.show-actuator=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

sendgrid.api.key=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
system.email=milkstoremanagement@gmail.com
